version: '3'

services:

  app:
    image: php:7.4-apache
    container_name: ${NAME}
    build: .
    networks:
        - web
    # Uncomment for local test
    # ports:
    # - "80:80"    
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.jrcandev.netlib.re`)"
        - "traefik.http.routers.${NAME}.entrypoints=websecure"
        - "traefik.http.routers.${NAME}.tls.certresolver=lets-encrypt"
    restart: always


networks:
  web:
    external: true
