version: '3'

services:

  database:
    image: mariadb:10.2
    container_name: ${NAME}_db
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}" 
    networks:
      - lan
    volumes: 
      - db:/var/lib/mysql

  app:
    image: php:7.4-apache
    container_name: ${NAME}
    build: .
    networks:
        - web
        - lan
    # Uncomment for local test
    # ports:
    # - "80:80"    
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.jrcandev.netlib.re`)"
        - "traefik.http.routers.${NAME}.entrypoints=websecure"
        - "traefik.http.routers.${NAME}.tls.certresolver=lets-encrypt"
    restart: always
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: database
      database__connection__user: "${MYSQL_USERNAME}"
      database__connection__password: "${MYSQL_PASSWORD}"
      database__connection__database: "${MYSQL_DATABASE}"

secrets:
  mysql-password:
    file: ./bd.password

networks:
  web:
    external: true
  lan:
    internal: true

volumes:
  db: {}