version: '3'

services:

  database:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '1234567abc'
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: '1234567abc'
    networks:
      - lan
    volumes: 
      - db:/var/lib/mysql

  app:
    image: ghost:4-alpine
    container_name: ${NAME}
    build: .
    networks:
        - web
        - lan
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.jrcandev.netlib.re`)"
        - "traefik.http.routers.${NAME}.entrypoints=websecure"
        - "traefik.http.routers.${NAME}.tls.certresolver=lets-encrypt"
    restart: always
    environment:
      DB_HOST: database
    
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: database
      database__connection__user: 'test'
      database__connection__password: '1234567abc'
      database__connection__database: 'testdb'
      url: https://tecoblog.ddns.net
      NODE_ENV: production

networks:
  web:
    external: true
  lan:
    internal: true

volumes:
  db: {}